### ISSUE TITLE
Please update helm

### ISSUE THREAD

**Issue by popey** [snapcrafters/helm#1]
There's a new upstream version of helm - 2.5.1. Please update the yaml accordingly. Thanks.

https://github.com/kubernetes/helm/releases

**Comment by Ads20000** [comment]
Thanks for pulling my PR for 2.6.0 and pushing to `candidate`. Should we push to `stable`? Has been sitting there for 8 days and I got no response on my call for testing in the forum...

**Comment by joedborg** [comment]
I've updated it and run through tests on a K8s cluster.  All working, so pushed to stable.

**Comment by Ads20000** [comment]
@popey can you close this Issue then please? :)

**Comment by popey** [comment]
🎉  🍻  💃  ✔  🎶  🎧  🍺
