### ISSUE TITLE
Helm missing `socat`

### ISSUE THREAD

**Issue by cprov** [snapcrafters/helm#17]
As mentioned in https://github.com/ubuntu/microk8s/issues/70, `socat` deb has to be installed manually in order to have a functional setup with `microk8s`.

Could it be embedded (staged) in the helm snap ?

**Comment by joedborg** [comment]
Should be fixed in https://github.com/snapcrafters/helm/pull/51

**Comment by joedborg** [comment]
Hi @cprov, we're now bundling `socat` with the Snap.  Thanks for raising the bug!
