### ISSUE TITLE
helm: command not found

### ISSUE THREAD

**Issue by BrunoQuaresma** [snapcrafters/helm#18]
I installed the helm but the bash does not recognize the command.

```
bruno@bruno-X555UB:~$ sudo snap install helm
snap "helm" is already installed, see 'snap help refresh'
bruno@bruno-X555UB:~$ helm
helm: command not found
bruno@bruno-X555UB:~$ 
```

**Comment by matohavo** [comment]
Try to open new console - it helped me.

**Comment by mapleoin** [comment]
This was an issue with my snap installation in Debian 9. I had to add the snap bins to my PATH:

```
# ~/.bashrc
PATH=$PATH:/snap/bin
```

**Comment by popey** [comment]
This appears to be a local issue which plagues a number of snaps on select distributions. I understand it's frustrating, but I believe the only workaround is starting a new shell, re-logging in or restarting. So closing the issue here.

**Comment by adarshaJha** [comment]
when i run **helm init** i got this 
Creating /home/adarsha/.helm 
Creating /home/adarsha/.helm/repository 
Creating /home/adarsha/.helm/repository/cache 
Creating /home/adarsha/.helm/repository/local 
Creating /home/adarsha/.helm/plugins 
Creating /home/adarsha/.helm/starters 
Creating /home/adarsha/.helm/cache/archive 
Creating /home/adarsha/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/adarsha/.helm.

`Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused`
