### ISSUE TITLE
Install previous version

### ISSUE THREAD

**Issue by gavinfish** [snapcrafters/helm#25]
How can I install previous version of helm like `2.9.1` by snap here?

**Comment by jtzemp** [comment]
Thanks for the work y'all do to package `helm` up as a snap! +1 to what @gavinfish said. It'd be really awesomesauce if y'all could maintain a channel* for each minor version of helm (assuming helm uses semver--their docs say they do).

See `snap info kubectl` for an example of what I mean. Then we could `snap install --channel=2.9 helm`. 

\* I'm pretty new to snap, so forgive me if I'm using the wrong terminology.

**Comment by simleo** [comment]
+1 from me as well. Just got hit by this:

```
Error: incompatible versions client[v2.13.0] server[v2.12.3]
```

And I have no control over the server, so I'm stuck.

**Comment by redixin** [comment]
Meanwhile users can download older versions from the main repository: https://github.com/helm/helm/releases

And still use `tar -zxf` in 2019

**Comment by simleo** [comment]
Using this in the meantime (**linux-amd64 only!**):

```bash
#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: $0 VERSION" 1>&2
    exit 1
fi
version=$1

curl -fSL https://storage.googleapis.com/kubernetes-helm/helm-v${version}-linux-amd64.tar.gz | tar xz -C /usr/local/bin/ --strip-components=1 linux-amd64/helm
```

Save to `/usr/local/bin/install_helm`, then:

```
chmod +x /usr/local/bin/install_helm
install_helm 2.12.3
```

**Comment by chicken231** [comment]
I ran this to downgrade my snap/helm installation:

```bash
snap switch --channel=2.13.1 helm
```

Output:

```
"helm" switched to the "2.13.1/stable" channel
```

**Comment by noomly** [comment]
Still no news on this?

**Comment by soujiro32167** [comment]
bump

**Comment by danielpcox** [comment]
This is also quite necessary for me. The current version of Helm behaves different with respect to my old templates, so the upgrade has broken some installations. I'll have to stop using the Snap until a new version fixes it.

**Comment by joedborg** [comment]
Hi everyone, this is something we're working on with snap tracks.  Feel free to comment on https://forum.snapcraft.io/t/helm-tracks-request/13978/5

**Comment by joedborg** [comment]
Hi all, thanks to everyone who has commented here.  Moving forward (starting at 2.16), we'll now track minor releases and update these only with the bug fixes as this shouldn't break compatibility.

If there is legitimate need for an earlier minor, I can look at adding it but I cannot make any guarantees.

**Comment by burka** [comment]
Thanks for the change! `snap install --classic --channel=2.16/stable helm` worked for me :-)
