### ISSUE TITLE
snap version of helm cannot find executables declared in kubectl config 

### ISSUE THREAD

**Issue by arjovanramshorst** [snapcrafters/helm#29]
Possibly related to #10 but I wanted to create a separate issue anyway to help future people with the same problem:

While trying to install helm (tiller) on an aws EKS cluster, it didn't work because it couldn't find the iam-aws-authenticator file in $PATH, which is used to authenticate. After a couple of hours of headscratching, I've tried using the binary install to reinstall helm, and it worked at once.

**Comment by joedborg** [comment]
Hi @arjovanramshorst, I need to look into why this is happening.  As this is a classic confinement snap, it should be able to access other binaries across your system.  Could you try forcing PATH when running the snap, please?  E.g.

```
PATH="/my/path:${PATH}" helm
```
