### ISSUE TITLE
Helm 2.14.0

### ISSUE THREAD

**Issue by Nox-404** [snapcrafters/helm#36]
Hello,
is it possible to have the `2.14` available ?

**Comment by Nox-404** [comment]
That was quite fast :) where can I see if it's available on snap ?

**Comment by popey** [comment]
It's building right now, it will land in the edge channel. So you can `snap refresh helm --edge` once you see 2.14.0 in the output of `snap info helm`.

**Comment by popey** [comment]
Once you get a chance to test it, let me know and I'll publish to stable.

**Comment by Nox-404** [comment]
testing right now

**Comment by Nox-404** [comment]
Seems ok to me !

**Comment by popey** [comment]
Thanks for testing, and for the initial report. I'll get it published to stable shortly.
