### ISSUE TITLE
Expose Tiller Binary

### ISSUE THREAD

**Issue by austince** [snapcrafters/helm#37]
Is there a way to also expose the tiller binary for running locally? This is helpful during development and also [the recommended way to use Helm with AWS EKS.](https://docs.aws.amazon.com/eks/latest/userguide/helm.html)

**Comment by austince** [comment]
@ldath here's the snap from the PR if you want to use it: 
[helm-pr41.zip](https://github.com/snapcrafters/helm/files/3664527/helm-pr41.zip)

**Comment by ldath** [comment]
Thanks

**Comment by joedborg** [comment]
Tiller exposed on builds in channels 2.15 and 2.16.  Access with `helm.tiller`.

**Comment by austince** [comment]
Hey @joedborg, sorry I never ran this until now, but I'm not finding the `helm.tiller` binary when installing from the 2.16 channel.

```
sudo snap install helm --channel=2.16/stable --classic
```

Is it not on the stable channel?

**Comment by joedborg** [comment]
@austince it should be, I'll take a look (it's branch v2).

**Comment by joedborg** [comment]
Morning @austince, please try again (after a refresh).  Not sure why it wasn't working before, but I've rebuilt and pushed the images and they seem to be good now.

**Comment by austince** [comment]
Just pulled, all good! Thanks @joedborg!
