### ISSUE TITLE
Missing option to install v3.* from beta channel

### ISSUE THREAD

**Issue by wojciech-kopras** [snapcrafters/helm#44]
In beta and edge channel there is only the same version as in stable "2.14.3". But there is available also beta version - currently "3.0.0.-beta.3" https://github.com/helm/helm/releases . Can it be published on beta channel?

**Comment by joedborg** [comment]
Yes, we'll be able to do that (especially now that 3 is stable).  Just need this https://forum.snapcraft.io/t/helm-tracks-request/13978/5

**Comment by joedborg** [comment]
The rest have been published.  Should be good to close this.
