### ISSUE TITLE
Is helm 3.* classic?

### ISSUE THREAD

**Issue by 0xErnie** [snapcrafters/helm#57]
I am new to snap and just installed helm with:
`sudo snap install helm --classic` from the [docs of helm 2](https://v2.helm.sh/docs/using_helm/#installing-helm)

To my surprise helm version 3.1.2 was installed.. rather fresh for a classic, is it?

Another surprise: The docs of helm v3 also suggest installing helm with "--classic" [link](https://helm.sh/docs/intro/install/)

My favourite would be having a real choice, like one has with [brew](https://formulae.brew.sh/formula/helm@2).

Greetings from Hamburg :)

**Comment by joedborg** [comment]
Hey @0xErnie,

I think there's some confusion around what `classic` means in this context.  When you add the flag to `snap install`, you are defining the confinement method (https://snapcraft.io/docs/snap-confinement), not the version of the snap that is installed.

If you want to select a different version of the snap, you can see the available ones with `snap info helm` and then use the `--channel` flag to set this.  E.g. 

```
sudo snap install helm --classic --channel=2.16
```

After which, you can change this with `snap refresh`.  E.g.

```
sudo snap refresh helm --channel 3.1
```

Hope this helps.
