### ISSUE TITLE
[Enhancement]: Release 3.8.1 to stable

### ISSUE THREAD

**Issue by falk-atos** [snapcrafters/helm#74]
### What changes would you like?

As the new version brings several improvements and is already widely used autside of snap I'd appreciate if the version could be bumped up :

**Comment by dingobar** [comment]
[Helm 3.9.0 was released](https://github.com/helm/helm/releases/tag/v3.9.0)

**Comment by merlijn-sebrechts** [comment]
Thanks for letting us know, we now have a much later version in stable, closing this as fixed!
